### ISSUE TITLE
Unable to format with clang due to python file error

### ISSUE THREAD

**Issue by h2110100** [bitst0rm-pub/Formatter#53]
So I've been trying to debug myself with no success. I have been trying to format a c++ file, but its not formatting, and giving me the following error;
```reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading python 3.3 plugin ayu.activation
reloading python 3.3 plugin ayu.Icons
reloading python 3.3 plugin Material Theme.MT
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.plugin
reloading plugin Formatter.__init__
reloading plugin Formatter.main
reloading python 3.3 plugin Terminus.main
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 327, in reload_plugin
    load_module(m)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 378, in load_module
    obj = t()
  File "C:\Users\The Fool\AppData\Roaming\Sublime Text\Packages\Formatter\core\smanager.py", line 169, in __init__
    self.session_manager = SessionManager(max_database_records=600)
  File "C:\Users\The Fool\AppData\Roaming\Sublime Text\Packages\Formatter\core\smanager.py", line 31, in __init__
    self.cleanup_session_file()
  File "C:\Users\The Fool\AppData\Roaming\Sublime Text\Packages\Formatter\core\smanager.py", line 82, in cleanup_session_file
    self.remove_old_entries()
  File "C:\Users\The Fool\AppData\Roaming\Sublime Text\Packages\Formatter\core\smanager.py", line 45, in remove_old_entries
    data = self.read_session_file()
  File "C:\Users\The Fool\AppData\Roaming\Sublime Text\Packages\Formatter\core\smanager.py", line 36, in read_session_file
    return json.load(f)
  File "./python3.8/json/__init__.py", line 293, in load
  File "./python3.8/encodings/cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 20588: character maps to <undefined>
plugins loaded
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 584, in init
    on_activated(view_id)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 975, in on_activated
    run_view_callbacks('on_activated', view_id)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "C:\Users\The Fool\AppData\Roaming\Sublime Text\Packages\Formatter\main.py", line 1058, in on_activated
    if self.query(common.config, False, 'layout', 'sync_scroll') and self.want_layout():
AttributeError: module 'Formatter.core.common' has no attribute 'config'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 975, in on_activated
    run_view_callbacks('on_activated', view_id)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "C:\Users\The Fool\AppData\Roaming\Sublime Text\Packages\Formatter\main.py", line 1058, in on_activated
    if self.query(common.config, False, 'layout', 'sync_scroll') and self.want_layout():
AttributeError: module 'Formatter.core.common' has no attribute 'config'
Package Control: Skipping automatic upgrade, last run at 2024-04-18 21:34:23, next run at 2024-04-19 05:34:23 or after
```

**Comment by h2110100** [comment]
Here is my settings file, all the paths seem to be correct, since it works on another editor.
```
{
  // Enable debug mode to view errors in the console.
  "debug": true,

  // Auto open the console panel whenever formatting failed.
  // This is useful when combined with "debug": true
  "open_console_on_failure": true,

  // Display results in the status bar.
  // The displayed abbreviation for the current settings mode:
  // PUS: Persistent User Settings
  // PQO: Persistent Quick Options
  // TQO: Temporary Quick Options
  "show_statusbar": true,

  // Display a real-time word and character count in the status bar.
  // By default, whitespace is not included in the character count.
  "show_words_count": {
    "enable": true,
    "ignore_whitespace_char": true
  },
  // THIRD-PARTY PLUGINS LEVEL
  "formatters": {
    "clangformat": {
            "name": "Clang",
            "type": "beautifier",
            "enable": true,
            "format_on_save": true,
            "format_on_paste": false,
            "new_file_on_format": false,
            "recursive_folder_format": {
                "enable": false,
                "exclude_folders_regex": [],
                "exclude_files_regex": [],
                "exclude_extensions": [],
                "exclude_syntaxes": []
            },
            "syntaxes": ["c", "cs", "c++", "cpp", "objc", "objc++", "js", "tsx", "jsx", "json", "java", "proto", "protodevel", "td", "sv", "svh", "v", "vh", "glsl"],
            "executable_path": ["C:/Program Files/Clang/clang-format/clang-format.exe"],
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/clang_format_general.yaml"
            }
        },
      },
    // "yapf": {
    //   "info": "https://github.com/google/yapf",
    //   "type": "beautifier",
    //   "disable": false,
    //   "format_on_save": true,
    //   "format_on_paste": false,
    //   "new_file_on_format": false,
    //   "recursive_folder_format": {
    //     "enable": false,
    //     "exclude_folders_regex": [],
    //     "exclude_files_regex": [],
    //     "exclude_extensions": [],
    //     "exclude_syntaxes": []
    //   },
    //   "syntaxes": [
    //     "python"
    //   ],
    //   "executable_path": "C:\\Program Files\\miniconda3\\Scripts\\yapf.exe",
    //   "config_path": {
    //     "default": "${packages}\\User\\formatter.assets\\config\\yapf_rc.yapf"
    //   }
    // },
}
```

**Comment by bitst0rm** [comment]
@h2110100 

Thanks for your bug report. To the issue:

>   File "C:\Users\The Fool\AppData\Roaming\Sublime Text\Packages\Formatter\core\smanager.py", line 36, in read_session_file
>     return json.load(f)
>   File "./python3.8/json/__init__.py", line 293, in load
>   File "./python3.8/encodings/cp1252.py", line 23, in decode
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 20588: character maps to <undefined>

It is `UnicodeDecodeError`.
I have fixed this to reading files in `'utf-8'` and released 1.4.5 to address this issue.

---
Your config is almost correct, with the only mistake being the use of `"name"` and `"type"`. These 2 keys are very important and only required to use with the `Generic` method. If you add them into config to use with the `Module` method, then Formatter will think you are using the `Generic` method, which is wrong.

I'd simplify your config a little bit, since you are using the `default` values, you can omid:
- "show_statusbar"
- "show_words_count"

like this:

```js
{
  "debug": true,  // For daily use, better use "status" instead of true. ("status" = debug your code, true = debug code of Formatter)
  "open_console_on_failure": true,

  // THIRD-PARTY PLUGINS LEVEL
  "formatters": {
    "clangformat": { // <- this UID already exists and it is the module method.
           //"name": "Clang",  // <-- IMPORTANT: omid this as you are not using the generic method.
           //"type": "beautifier",  // <-- IMPORTANT: omid this as you are not using the generic method.
            "enable": true,
            "format_on_save": true,
            "format_on_paste": false,
            "new_file_on_format": false,
            "recursive_folder_format": {
                "enable": false,
                "exclude_folders_regex": [],
                "exclude_files_regex": [],
                "exclude_extensions": [],
                "exclude_syntaxes": []
            },
            "syntaxes": ["c", "cs", "c++", "cpp", "objc", "objc++", "js", "tsx", "jsx", "json", "java", "proto", "protodevel", "td", "sv", "svh", "v", "vh", "glsl"],
            "executable_path": ["clang-format"],  // <-- If the exe is on the PATH, you can even simplify this to use cross-platform.
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/clang_format_general.yaml"
            }
        },
}
```

I strongly do **_not_** recommend using the `Generic method` for `clangformat` as it needs to be hacked deeper to detect syntax of input file.
In the case you would like to design the bridge yourself, then the `Generic method` would be so (as example):

```js
{
  "debug": true,
  "open_console_on_failure": true,

  // THIRD-PARTY PLUGINS LEVEL
  "formatters": {
    "clng": { // <- Choose a different UID since "clangformat" already exists.
           "name": "Clang",  // <-- IMPORTANT: required.
           "type": "beautifier",  // <-- IMPORTANT:  required.
           "args": ["{{e}}", "--style=file:", "{{c}}", "--"], // <-- IMPORTANT: required.

            "enable": true,
            "format_on_save": true,
            "format_on_paste": false,
            "new_file_on_format": false,
            "recursive_folder_format": {
                "enable": false,
                "exclude_folders_regex": [],
                "exclude_files_regex": [],
                "exclude_extensions": [],
                "exclude_syntaxes": []
            },
            "syntaxes": ["c", "cs", "c++", "cpp", "objc", "objc++", "js", "tsx", "jsx", "json", "java", "proto", "protodevel", "td", "sv", "svh", "v", "vh", "glsl"],
            "executable_path": ["C:/Program Files/Clang/clang-format/clang-format.exe"],
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/clang_format_general.yaml"
            }
        },
}
```

---
For more convenience, you can use the new feature: [auto-detect formatting](https://github.com/bitst0rm-pub/Formatter?tab=readme-ov-file#auto-detect-formatting) with just one-command if you want:

```js
{
  "debug": true,
  "open_console_on_failure": true,

    "auto_format": {
        "config": {
            "format_on_save": false,
            "format_on_paste": false
        },
        "json": {
            "uid": "jsbeautifier"
        },
        "html": {
            "uid": "jsbeautifier",
            "exclude_syntaxes": {
                "html": ["markdown"]
            }
        },
        "c++": {
            "uid": "clangformat"
        }
    },

  // THIRD-PARTY PLUGINS LEVEL
  "formatters": {
    "clangformat": {
            "enable": true,
            "format_on_save": true,
            "format_on_paste": false,
            "new_file_on_format": false,
            "recursive_folder_format": {
                "enable": false,
                "exclude_folders_regex": [],
                "exclude_files_regex": [],
                "exclude_extensions": [],
                "exclude_syntaxes": []
            },
            "syntaxes": ["c", "cs", "c++", "cpp", "objc", "objc++", "js", "tsx", "jsx", "json", "java", "proto", "protodevel", "td", "sv", "svh", "v", "vh", "glsl"],
            "executable_path": ["C:/Program Files/Clang/clang-format/clang-format.exe"],
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/clang_format_general.yaml"
            }
        },
}
```

**Comment by h2110100** [comment]
Thanks, it fixed it not formatting.

**Comment by h2110100** [comment]
I have another issue that I'm not sure if it belongs here.
My clang format file:
BasedOnStyle:  Google
SeparateDefinitionBlocks: Always
RemoveBracesLLVM: true
IndentWidth:     4
TabWidth:        4
UseTab:          Always
AllowShortFunctionsOnASingleLine: true
ColumnLimit: 150


It should format into something like
```
#include <bits/stdc++.h>
using namespace std;

vector<int> mergesort(vector<int> v) {
	if (v.size() == 1) return v;
	vector<int> left, right;
	for (int i = 0; i < v.size() / 2; i++) left.push_back(v[i]);
	for (int i = v.size() / 2; i < v.size(); i++) right.push_back(v[i]);
	left = mergesort(left);
	right = mergesort(right);
	vector<int> res;
	int i = 0, j = 0;
	while (i < left.size() && j < right.size())
		if (left[i] < right[j])
			res.push_back(left[i++]);
		else
			res.push_back(right[j++]);
	while (i < left.size()) res.push_back(left[i++]);
	while (j < right.size()) res.push_back(right[j++]);
	return res;
}

int fib(int n) {
	if (n == 0) return 0;
	if (n == 1) return 1;
	return fib(n - 1) + fib(n - 2);
}

int bubblesort(int a[]) {
	int n = sizeof(a) / sizeof(a[0]);
	for (int i = 0; i < n; i++)
		for (int j = 0; j < n - i - 1; j++)
			if (a[j] > a[j + 1]) swap(a[j], a[j + 1]);
	return 0;
}

void fastio() {
	ios::sync_with_stdio(false);
	cin.tie(nullptr);
	cout.tie(nullptr);
}

int main() {
	ios::sync_with_stdio(false);
	cin.tie(nullptr);
	cout.tie(nullptr);

	cout << "Hello, World!\n";
	for (int x : mergesort({9, 8, 7, 6, 5})) cout << x << " ";

	return 0;
}
```

Instead, its formatting into:
```
#include <bits/stdc++.h>
using namespace std;

vector<int> mergesort(vector<int> v) {
  if (v.size() == 1)
    return v;
  vector<int> left, right;
  for (int i = 0; i < v.size() / 2; i++)
    left.push_back(v[i]);
  for (int i = v.size() / 2; i < v.size(); i++)
    right.push_back(v[i]);
  left = mergesort(left);
  right = mergesort(right);
  vector<int> res;
  int i = 0, j = 0;
  while (i < left.size() && j < right.size())
    if (left[i] < right[j])
      res.push_back(left[i++]);
    else
      res.push_back(right[j++]);
  while (i < left.size())
    res.push_back(left[i++]);
  while (j < right.size())
    res.push_back(right[j++]);
  return res;
}

int fib(int n) {
  if (n == 0)
    return 0;
  if (n == 1)
    return 1;
  return fib(n - 1) + fib(n - 2);
}

int bubblesort(int a[]) {
  int n = sizeof(a) / sizeof(a[0]);
  for (int i = 0; i < n; i++)
    for (int j = 0; j < n - i - 1; j++)
      if (a[j] > a[j + 1])
        swap(a[j], a[j + 1]);
  return 0;
}

void fastio() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);
  cout.tie(nullptr);
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);
  cout.tie(nullptr);

  cout << "Hello, World!\n";
  for (int x : mergesort({9, 8, 7, 6, 5}))
    cout << x << " ";

  return 0;
}
```

It worked before I fixed the error. Do you happen to know why?

**Comment by h2110100** [comment]
I think there's something wrong with the indenting, because the rest of the formatting seems to work.

**Comment by bitst0rm** [comment]
@h2110100 

The codebase for processing formatting hasn't been modified since a long time. Moreover, the recent fixes were unrelated to formatting; they targeted to other features. I do not have any clue why it's producing unexpected results on Windows while functioning correctly on Mac. At the moment when you request formatting, Formatter no longer influences the result. The third-party plugin is now responsible for it. In this case it is `clang-format`.

On the Mac, I tested with the
- old `clang-format `version `15.0.7` (`18.1.4` is the latest version, but it failed to compile on my machine)
- Sublime Text `space: 4`
- Formatter `1.4.5`

_clang_format_google_rc_test.yaml_

```yaml
BasedOnStyle: Google
SeparateDefinitionBlocks: Always
RemoveBracesLLVM: true
IndentWidth: 4
TabWidth: 4
UseTab: Always
AllowShortFunctionsOnASingleLine: true
ColumnLimit: 150
```

test.cpp (copy&paste from your post)
```cpp
#include <bits/stdc++.h>
using namespace std;

vector<int> mergesort(vector<int> v) {
  if (v.size() == 1)
    return v;
  vector<int> left, right;
  for (int i = 0; i < v.size() / 2; i++)
    left.push_back(v[i]);
  for (int i = v.size() / 2; i < v.size(); i++)
    right.push_back(v[i]);
  left = mergesort(left);
  right = mergesort(right);
  vector<int> res;
  int i = 0, j = 0;
  while (i < left.size() && j < right.size())
    if (left[i] < right[j])
      res.push_back(left[i++]);
    else
      res.push_back(right[j++]);
  while (i < left.size())
    res.push_back(left[i++]);
  while (j < right.size())
    res.push_back(right[j++]);
  return res;
}

int fib(int n) {
  if (n == 0)
    return 0;
  if (n == 1)
    return 1;
  return fib(n - 1) + fib(n - 2);
}

int bubblesort(int a[]) {
  int n = sizeof(a) / sizeof(a[0]);
  for (int i = 0; i < n; i++)
    for (int j = 0; j < n - i - 1; j++)
      if (a[j] > a[j + 1])
        swap(a[j], a[j + 1]);
  return 0;
}

void fastio() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);
  cout.tie(nullptr);
}

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);
  cout.tie(nullptr);

  cout << "Hello, World!\n";
  for (int x : mergesort({9, 8, 7, 6, 5}))
    cout << x << " ";

  return 0;
}
```


and got the result:
```cpp
#include <bits/stdc++.h>
using namespace std;

vector<int> mergesort(vector<int> v) {
    if (v.size() == 1) return v;
    vector<int> left, right;
    for (int i = 0; i < v.size() / 2; i++) left.push_back(v[i]);
    for (int i = v.size() / 2; i < v.size(); i++) right.push_back(v[i]);
    left = mergesort(left);
    right = mergesort(right);
    vector<int> res;
    int i = 0, j = 0;
    while (i < left.size() && j < right.size())
        if (left[i] < right[j])
            res.push_back(left[i++]);
        else
            res.push_back(right[j++]);
    while (i < left.size()) res.push_back(left[i++]);
    while (j < right.size()) res.push_back(right[j++]);
    return res;
}

int fib(int n) {
    if (n == 0) return 0;
    if (n == 1) return 1;
    return fib(n - 1) + fib(n - 2);
}

int bubblesort(int a[]) {
    int n = sizeof(a) / sizeof(a[0]);
    for (int i = 0; i < n; i++)
        for (int j = 0; j < n - i - 1; j++)
            if (a[j] > a[j + 1]) swap(a[j], a[j + 1]);
    return 0;
}

void fastio() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    cout.tie(nullptr);
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    cout.tie(nullptr);

    cout << "Hello, World!\n";
    for (int x : mergesort({9, 8, 7, 6, 5})) cout << x << " ";

    return 0;
}

```

**Comment by bitst0rm** [comment]
and with `IndentWidth: 8`

clang_format_google_rc_test.yaml
```yaml
BasedOnStyle: Google
SeparateDefinitionBlocks: Always
RemoveBracesLLVM: true
IndentWidth: 8
TabWidth: 4
UseTab: Always
AllowShortFunctionsOnASingleLine: true
ColumnLimit: 150
```

```cpp
#include <bits/stdc++.h>
using namespace std;

vector<int> mergesort(vector<int> v) {
        if (v.size() == 1) return v;
        vector<int> left, right;
        for (int i = 0; i < v.size() / 2; i++) left.push_back(v[i]);
        for (int i = v.size() / 2; i < v.size(); i++) right.push_back(v[i]);
        left = mergesort(left);
        right = mergesort(right);
        vector<int> res;
        int i = 0, j = 0;
        while (i < left.size() && j < right.size())
                if (left[i] < right[j])
                        res.push_back(left[i++]);
                else
                        res.push_back(right[j++]);
        while (i < left.size()) res.push_back(left[i++]);
        while (j < right.size()) res.push_back(right[j++]);
        return res;
}

int fib(int n) {
        if (n == 0) return 0;
        if (n == 1) return 1;
        return fib(n - 1) + fib(n - 2);
}

int bubblesort(int a[]) {
        int n = sizeof(a) / sizeof(a[0]);
        for (int i = 0; i < n; i++)
                for (int j = 0; j < n - i - 1; j++)
                        if (a[j] > a[j + 1]) swap(a[j], a[j + 1]);
        return 0;
}

void fastio() {
        ios::sync_with_stdio(false);
        cin.tie(nullptr);
        cout.tie(nullptr);
}

int main() {
        ios::sync_with_stdio(false);
        cin.tie(nullptr);
        cout.tie(nullptr);

        cout << "Hello, World!\n";
        for (int x : mergesort({9, 8, 7, 6, 5})) cout << x << " ";

        return 0;
}

```

**Comment by h2110100** [comment]
I think I know why its doing it on my pc, its because its not even reading the config file. I changed it to something that doesn't exists and its still formatting, without any error. It does print successful though.

```
▋[Formatter](main.py#L88): [INFO] Formatter version: 1.4.5 (Python 3.8.12)
▋[Formatter](main.py#L89): [DEBUG] Plugin initialization succeeded.
reloading settings Packages/Formatter/Formatter.sublime-settings
▋[Formatter](main.py#L1186): [DEBUG] "format_on_save" enabled for ID: clangformat, using syntax: c++
▋[Formatter](common.py#L979): [INFO] System environments:
{
    "ALLUSERSPROFILE": "C:\\ProgramData",
    "APPDATA": "C:\\Users\\The Fool\\AppData\\Roaming",
    "ASL.LOG": "Destination=file",
    "CHOCOLATEYINSTALL": "C:\\ProgramData\\chocolatey",
    "CHOCOLATEYLASTPATHUPDATE": "133517795185084492",
    "CHOCOLATEYTOOLSLOCATION": "C:\\tools",
    "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
    "COMMONPROGRAMFILES(X86)": "C:\\Program Files (x86)\\Common Files",
    "COMMONPROGRAMW6432": "C:\\Program Files\\Common Files",
    "COMPUTERNAME": "ADMINISTRATOR",
    "COMSPEC": "C:\\Windows\\system32\\cmd.exe",
    "DRIVERDATA": "C:\\Windows\\System32\\Drivers\\DriverData",
    "EFC_5960": "1",
    "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
    "FPS_BROWSER_USER_PROFILE_STRING": "Default",
    "HOMEDRIVE": "C:",
    "HOMEPATH": "\\Users\\The Fool",
    "LOCALAPPDATA": "C:\\Users\\The Fool\\AppData\\Local",
    "LOGONSERVER": "\\\\ADMINISTRATOR",
    "NUMBER_OF_PROCESSORS": "16",
    "ONEDRIVE": "C:\\Users\\The Fool\\OneDrive",
    "OS": "Windows_NT",
    "PATH": "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\cf-tool;C:\\Program Files\\mingw64\\bin;C:\\Program Files\\micro-2.0.13;C:\\Program Files\\fzf-0.45.0-windows_amd64;C:\\Program Files\\miniconda3;C:\\Program Files\\miniconda3\\Scripts;C:\\Program Files\\Clang\\clang-format;C:\\Program Files\\Wolfram Research\\WolframScript\\;C:\\Program Files\\Cloudflare\\Cloudflare WARP\\;C:\\Users\\The Fool\\AppData\\Local\\Microsoft\\WindowsApps;C:\\tools\\neovim\\nvim-win64\\bin",
    "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
    "PROCESSOR_ARCHITECTURE": "AMD64",
    "PROCESSOR_IDENTIFIER": "AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD",
    "PROCESSOR_LEVEL": "25",
    "PROCESSOR_REVISION": "7401",
    "PROGRAMDATA": "C:\\ProgramData",
    "PROGRAMFILES": "C:\\Program Files",
    "PROGRAMFILES(X86)": "C:\\Program Files (x86)",
    "PROGRAMW6432": "C:\\Program Files",
    "PSMODULEPATH": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
    "PUBLIC": "C:\\Users\\Public",
    "SESSIONNAME": "Console",
    "SYSTEMDRIVE": "C:",
    "SYSTEMROOT": "C:\\Windows",
    "TEMP": "C:\\Users\\THEFOO~1\\AppData\\Local\\Temp",
    "TMP": "C:\\Users\\THEFOO~1\\AppData\\Local\\Temp",
    "USERDOMAIN": "ADMINISTRATOR",
    "USERDOMAIN_ROAMINGPROFILE": "ADMINISTRATOR",
    "USERNAME": "The Fool",
    "USERPROFILE": "C:\\Users\\The Fool",
    "WINDIR": "C:\\Windows",
    "SSL_CERT_FILE": "C:\\Program Files\\Sublime Text\\Lib\\python3\\certifi\\cacert.pem",
    "NO_COLOR": "1"
}
▋[Formatter](common.py#L984): [INFO] Current mode: User Settings
▋[Formatter](formatter.py#L23): [DEBUG] Target: D:\IO\Code\codebreaker.cpp
▋[Formatter](formatter.py#L24): [DEBUG] Scope: source.c++ meta.preprocessor.include.c++ keyword.control.import.include.c++ 
▋[Formatter](formatter.py#L25): [DEBUG] Syntax: c++
▋[Formatter](formatter.py#L26): [DEBUG] UID: clangformat (method: module)
▋[Formatter](common.py#L338): [DEBUG] User executable found: C:\Program Files\LLVM\bin\clang-format.exe
▋[Formatter](common.py#L515): [WARNING] Setting key "config_path" must be a non-empty dict: None
▋[Formatter](common.py#L517): [INFO] Plugin default or per-project config will be used instead if available.
▋[Formatter](formatter_clangformat.py#L75): [DEBUG] Current arguments: ['C:\\Program Files\\LLVM\\bin\\clang-format.exe', '--assume-filename=dummy.cpp', '--']
▋[Formatter](main.py#L539): [STATUS] 🎉 Formatting successful. 🥳✨

Package Control: Skipping automatic upgrade, last run at 2024-04-20 20:57:11, next run at 2024-04-21 04:57:11 or after
```

**Comment by bitst0rm** [comment]
> ▋[Formatter](common.py#L515): [WARNING] Setting key "config_path" must be a non-empty dict: None

ahh, i see… the type check for `"config_path"` raises an alarm.
In this case both the `type` and the `existence` of config_path are incorrect: `"config_path": null,`

It must be a non-empty dict `"config_path": {"key":value},`

> ▋[Formatter](common.py#L517): [INFO] Plugin default or per-project config will be used instead if available.

then, Formatter will process formatting without any config argument using clang-format `default` config and raise a warning for user about this.

▋[Formatter](formatter_clangformat.py#L75): [DEBUG] Current arguments: ['C:\\Program Files\\LLVM\\bin\\clang-format.exe', '--assume-filename=dummy.cpp', '--']

we can see, the config argument `'--style=file:'` is missing here`, clang-format does everything with its own config, if available.

So everything is fine, it is by design that Formatter will run without raising any error - but printing warning  and info - by missing user config.

**Comment by h2110100** [comment]
Fixed it, also my ST had its default to syntax for c++ to have indent with spaces & indent width 2, so it might be overriding formatter. Thanks for your time.
![image](https://github.com/bitst0rm-pub/Formatter/assets/104179455/68f58a16-f182-4777-a08a-c1714465dee6)

**Comment by bitst0rm** [comment]
You are welcome.
Since ST4 i have to set Sublime space too, if I recall with ST3 it was not so.
Thanks for your nice conversation too.
