### ISSUE TITLE
Prettier not working on windows

### ISSUE THREAD

**Issue by andrejohansson** [bitst0rm-pub/Formatter#6]
## Describe the bug:
Installation needs explaining perhaps.

## Steps to reproduce:

1. Installed Formatter using package control
1. Installed prettier using ``yarn global add prettier``
1. Enabled Formatter debug
1. Run ``Formatter: Beautify With Prettier``
1. Crash, relevant console output is below.

## Expected behavior:

1. The file to be formatted

## Current behavior:

No formatting is done since it seems the way text is passed on to prettier is not working by default install methods. Do I need to do anything else to have paths working with prettier? Running the command ``\Desktop> prettier .\test.json`` outputs a perfectly fine formatted file.

## Environment:

  - Sublime Text version: 3.2.1
  - Formatter version: 0.1.6
  - Plugins used (name, version):
  - Configuration (plugin, Formatter): prettier 1.18.2
  - Operating System: Windows 10

## Code sample:

Any unformatted json/js.

## Log report:

```
▋[Formatter](Thread-25:formatter.py#L83): [DEBUG] Target: (view)
▋[Formatter](Thread-25:formatter.py#L84): [DEBUG] Scope: source.js meta.block.js punctuation.section.block.begin.js 
▋[Formatter](Thread-25:formatter.py#L85): [DEBUG] Syntax: js
▋[Formatter](Thread-25:formatter.py#L86): [DEBUG] Formatter ID: prettier
▋[Formatter](Thread-25:common.py#L215): [DEBUG] Interpreter: C:\Program Files\nodejs\node.exe
▋[Formatter](Thread-25:common.py#L249): [DEBUG] Config [default]: C:\Users\AndréJohansson\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\config\prettierrc.json
▋[Formatter](Thread-25:formatter_prettier.py#L83): [ERROR] File not formatted due to an error (errno=1): "C:\Users\AndréJohansson\AppData\Local\Yarn\bin\prettier.cmd:1

@"%~dp0\..\Data\global\node_modules\.bin\prettier.cmd"   %*

^



SyntaxError: Invalid or unexpected token

    at Module._compile (internal/modules/cjs/loader.js:703:23)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)

    at Module.load (internal/modules/cjs/loader.js:628:32)

    at Function.Module._load (internal/modules/cjs/loader.js:555:12)

    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)

    at internal/main/run_main_module.js:17:11

"
▋[Formatter](Thread-25:main.py#L118): [DEBUG] Formatting failed. 💣💥😢
```

**Comment by OdinTech3** [comment]
Has anyone resolved this problem yet?

**Comment by OdinTech3** [comment]
@andrejohansson @bitst0rm I figured out that if you use the path to the `bin-prettier.js` file for prettier as the `executable_path` that the problem gets resolved. Unfortunately formatting `JSON` is not possible or maybe I am missing something.
