### ISSUE TITLE
An error occurred after the upgrade

### ISSUE THREAD

**Issue by husanjun** [bitst0rm-pub/Formatter#65]
```
Traceback (most recent call last):
  File "F:\Sublime Text\Lib\python38\sublime_plugin.py", line 970, in on_activated
    run_view_callbacks('on_activated', view_id)
  File "F:\Sublime Text\Lib\python38\sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "F:\Sublime Text\Lib\python38\sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "F:\Sublime Text\Data\Packages\Formatter\plugin\formatter_listener.py", line 23, in on_activated
    ConfigHandler.project_config_overwrites_config()
  File "F:\Sublime Text\Data\Packages\Formatter\core\common.py", line 1224, in project_config_overwrites_config
    StringHandler.update_json_recursive(json_data=project_config, update_data=project_settings)
  File "F:\Sublime Text\Data\Packages\Formatter\core\common.py", line 891, in update_json_recursive
    if key in json_data and isinstance(value, dict) and isinstance(json_data[key], dict):
  File "F:\Sublime Text\Data\Packages\Formatter\core\common.py", line 45, in __getitem__
    raise RuntimeError('Direct access to CONFIG is not allowed. Use "OptionHandler.query(CONFIG, ...)" or "self.query(CONFIG, ...)" instead.')
RuntimeError: Direct access to CONFIG is not allowed. Use "OptionHandler.query(CONFIG, ...)" or "self.query(CONFIG, ...)" instead.
```

**Comment by bitst0rm** [comment]
Hi @husanjun 

Thank you for your bug report.
Could you please go to the `core > common.py` and post the line 33 for me to see what is stay here:
` _allowed_keys_for_get = [...]`

or could you please clone the `master` branch to see if the bug is gone.

Thanks!
I think i was going to push the wrong commit.

**Comment by husanjun** [comment]
```
_allowed_keys_for_get = ['custom_modules', 'custom_modules_manifest', 'formatters', 'STOP', 'environ', 'quick_options']
```

hope it helps

**Comment by bitst0rm** [comment]
Thanks @husanjun 
I could reproduce the issue and have fixed it in the master branch.
I am also releasing the new version address this issue so you can use it yet.

Edit: the new version is out on the way to Package Control

Thanks for your efforts!

---
The lastest version includes a new feature for auto format file to chain multi formatters in a single run like:
```
{
    // Comments are allowed.
    "python": ["isort", "black"],  // chaining sequentially in a single run, type list
    "json": "jsbeautifier",        // as type string
    "php": {                       // OR as type dictionary
        "uid": "phpcsfixer"
    },
    "html": {                      // dict can be used as a list item in chaining list
        "uid": "jsbeautifier",
        "exclude_syntaxes": {
            "html": ["markdown"]
        }
    }
}
```
